// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdsaxbxmptzzhyesgtwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkc2F4YnhtcHR6emh5ZXNndHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDMxODQsImV4cCI6MjA2NzU3OTE4NH0.5Xwu5lDEqc5LE4J4fsj6HwTsD6cMSMeA2U_CxmDrsYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});